"""Add fields to WeatherQueries model

Revision ID: acc06377f128
Revises: d2ed6c7c615a
Create Date: 2025-11-25 17:10:40.587658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc06377f128'
down_revision: Union[str, Sequence[str], None] = 'd2ed6c7c615a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_queries', sa.Column('city', sa.String(), nullable=True))
    op.add_column('weather_queries', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('weather_queries', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_weather_queries_city'), 'weather_queries', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_queries_city'), table_name='weather_queries')
    op.drop_column('weather_queries', 'description')
    op.drop_column('weather_queries', 'temperature')
    op.drop_column('weather_queries', 'city')
    # ### end Alembic commands ###
